Carbon:
  Dialog:
    # The tag name of the title
    titleTagName: h2

    # By default, the dialog behaves as a dialog: it is closable with
    # the ESC key, and by clicking the backdrop. However, it is possible
    # to make it work like a "modal", which would remove these features.
    modal: false

    # If set to false, no close button will be shown
    closeButton: '&times;'

    includeCSS: true
    includeJS: true

Neos:
  Neos:
    fusion:
      autoInclude:
        Carbon.Dialog: true

# Don't block the modal if Sandstorm.CookiePunch ist installed
Sandstorm:
  CookiePunch:
    blocking:
      tagPatterns:
        script:
          'Carbon/Carbon.Dialog':
            block: false
